categories:
  - title: '💥 Breaking changes'
    label: 'Breaking changes'
  - title: '🐛 Major bug fixes'
    label: 'Major bug fix'
  - title: '✨ Major features and improvements'
    label: 'Major feature'
  - title: '🐛 Fixes'
    label: 'Bugfix'
  - title: '✨ Features'
    label: 'Feature'
  - title: '🧭 Changes'
    label: 'Enhancement'
  - title: '✅ Chore'
    labels:
      - 'Refactor'
      - 'chore'
  - title: '📦 Dependency updates'
    labels:
      - 'Renovate'
      - 'Dependency updates'
  - title: '📝 Documentation updates'
    label: 'documentation'
  - title: '🚦 Tests'
    label: 'tests'
exclude-labels:
  - skip-changelog
  - invalid
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&@'
template: |
  $CHANGES
tag-template: $NEXT_PATCH_VERSION
version-template: $MAJOR.$MINOR.$PATCH
name-template: $NEXT_PATCH_VERSION
  
autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
      - '*.adoc'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'Bugfix'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'Feature'
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
    title:
      - '/feat/i'
      - '/feature/i'
  - label: 'chore'
    branch:
      - '/chore\/.+/'
      - '/refactor\/.+/'
    title:
      - '/chore/i'
      - '/refactor\/.+/'
  - label: 'tests'
    branch:
      - '/tests\/.+/'
    title:
      - '/tests/i'
  - label: 'Ready for Review'
    body:
      - '\Z'
      - '.'      
